//+------------------------------------------------------------------+
//|                                                   SafeTrendEA.mq5 |
//|                                   Copyright 2026, Generated by Claude |
//+------------------------------------------------------------------+
#property copyright "2026"
#property version   "1.00"
#property description "Self-contained, restart-safe Expert Advisor template."
#property description "Strategy: EMA crossover with ATR-based SL/TP and trailing stop."
#property description "Only ever opens/modifies/closes trades tagged with its own magic number."
#property description "Works on any symbol/timeframe it is attached to."

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>

//============================================================================
// DESIGN NOTES (read before deploying)
//
// 1) RESTART / RECOVERY SAFETY
//    Open positions and pending orders already live on the trade server and
//    terminal, so they survive an MT5 restart on their own. This EA never
//    keeps its own external "memory" of what it has open; instead, on every
//    tick it re-derives everything it needs (which positions are its own,
//    their volume/SL/TP/type) directly from PositionsTotal()/PositionGetTicket().
//    That means there is nothing to "lose" or desync if the terminal, VPS,
//    or EA is restarted - it simply resumes managing whatever positions
//    match its Symbol + Magic Number.
//    The only local state is the "last processed bar" timestamp, which is
//    intentionally re-armed (not restored) on every (re)start so the EA
//    waits for the NEXT fully-closed bar before evaluating a new signal,
//    rather than possibly reacting to a stale/ambiguous crossover the
//    instant it is attached or the terminal comes back up.
//
// 2) NON-INTERFERENCE WITH OTHER EAs / MANUAL TRADES
//    Every position/order lookup filters on BOTH the current chart symbol
//    AND InpMagicNumber. The EA never uses "close all" style calls and never
//    touches a ticket it did not verify belongs to it. It also does not use
//    Comment() (which is shared, chart-wide, and would clobber other EAs'
//    on-chart text) - all status/diagnostic output goes to the Experts log.
//
// 3) SYMBOL INDEPENDENCE
//    No symbol name, digit count, or point value is hard-coded. All price,
//    lot, tick-value and stop-level math is pulled live from SymbolInfoXxx()
//    for _Symbol, so the same compiled EA behaves correctly on any symbol
//    it is attached to (FX, metals, indices, crypto CFDs, etc.), regardless
//    of digits, lot step, or contract size.
//
// 4) EFFICIENCY
//    Indicator handles are created once (OnInit) and released once
//    (OnDeinit) - never recreated per tick. Indicator values are pulled
//    only once per completed bar (not per tick). Open positions are scanned
//    exactly once per tick (ScanOwnPositions), and that single pass both
//    updates trailing stops AND caches the counts used later in the same
//    tick to decide whether a new trade may be opened - avoiding a second
//    loop over PositionsTotal().
//
// 5) CUSTOMIZING THE STRATEGY
//    All entry-signal logic lives in CheckForNewSignal(). Replace the
//    EMA-crossover block there with your own conditions; the surrounding
//    risk-sizing, order-sending, trailing-stop and safety framework can be
//    reused unchanged.
//============================================================================

//--- General / identification
input ulong  InpMagicNumber      = 123456;    // Magic number (must be unique per EA instance on a symbol)
input string InpTradeComment     = "SafeTrendEA"; // Comment attached to orders/positions

//--- Order execution / safety
input ulong  InpSlippagePoints   = 20;        // Max allowed slippage / deviation (points)
input uint   InpMaxSpreadPoints  = 50;        // Max spread allowed to OPEN a new trade (points), 0 = no limit
input int    InpMaxRetries       = 3;         // Max retry attempts on requote/price errors
input int    InpRetryDelayMs     = 300;       // Delay between retries (milliseconds)

//--- Strategy: EMA crossover (example signal - replace as needed)
input ENUM_TIMEFRAMES     InpTimeframe      = PERIOD_H1;   // Signal timeframe
input int                 InpFastMAPeriod   = 10;          // Fast EMA period
input int                 InpSlowMAPeriod   = 30;          // Slow EMA period
input ENUM_MA_METHOD      InpMAMethod       = MODE_EMA;    // MA method
input ENUM_APPLIED_PRICE  InpAppliedPrice   = PRICE_CLOSE; // MA applied price
input int                 InpATRPeriod      = 14;          // ATR period (for SL/TP/trailing sizing)

//--- Risk management
input double InpRiskPercent      = 1.0;   // Risk per trade, % of balance (0 = use fixed lot instead)
input double InpFixedLot         = 0.10;  // Fixed lot size (used when InpRiskPercent <= 0, or as fallback)
input double InpATRMultiplierSL  = 2.0;   // Stop loss distance  = ATR * this
input double InpATRMultiplierTP  = 3.0;   // Take profit distance = ATR * this (0 = no take profit)
input int    InpMaxPositions     = 1;     // Max concurrent own positions per direction

//--- Trailing stop
input bool   InpUseTrailingStop      = true;  // Enable trailing stop
input double InpTrailingATRMultiplier = 1.5;  // Trail distance = ATR * this
input double InpTrailingStepATR       = 0.2;  // Minimum improvement (ATR * this) before moving SL again

//============================================================================
// Globals
//============================================================================
CTrade         trade;
CPositionInfo  m_position;

int      g_handleFastMA = INVALID_HANDLE;
int      g_handleSlowMA = INVALID_HANDLE;
int      g_handleATR    = INVALID_HANDLE;

datetime g_lastBarTime  = 0;      // last bar timestamp already processed for signals
double   g_lastATR      = 0.0;    // ATR value of the last fully closed bar (refreshed once per bar)

int      g_ownTotal     = 0;      // own open positions on this symbol (this tick's scan)
int      g_ownBuyCount  = 0;
int      g_ownSellCount = 0;

//+------------------------------------------------------------------+
//| Expert initialization                                             |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- validate inputs
   if(InpMagicNumber == 0)
   {
      Print("InpMagicNumber must be non-zero so this EA never manages manual/other-EA trades.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpFastMAPeriod <= 0 || InpSlowMAPeriod <= 0 || InpFastMAPeriod >= InpSlowMAPeriod)
   {
      Print("Invalid MA periods: fast period must be > 0 and less than slow period.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpATRPeriod <= 0)
   {
      Print("InpATRPeriod must be greater than zero.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpFixedLot <= 0.0)
   {
      Print("InpFixedLot must be greater than zero.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpRiskPercent < 0.0)
   {
      Print("InpRiskPercent cannot be negative.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpMaxPositions <= 0)
   {
      Print("InpMaxPositions must be at least 1.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpATRMultiplierSL <= 0.0)
   {
      Print("InpATRMultiplierSL must be greater than zero.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   //--- configure trading helper: scoped to our own magic number only
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippagePoints);
   trade.SetTypeFillingBySymbol(_Symbol);
   trade.SetAsyncMode(false); // synchronous sends so we can react to the result immediately

   //--- create indicator handles once
   g_handleFastMA = iMA(_Symbol, InpTimeframe, InpFastMAPeriod, 0, InpMAMethod, InpAppliedPrice);
   g_handleSlowMA = iMA(_Symbol, InpTimeframe, InpSlowMAPeriod, 0, InpMAMethod, InpAppliedPrice);
   g_handleATR    = iATR(_Symbol, InpTimeframe, InpATRPeriod);

   if(g_handleFastMA == INVALID_HANDLE || g_handleSlowMA == INVALID_HANDLE || g_handleATR == INVALID_HANDLE)
   {
      PrintFormat("Failed to create indicator handle(s). Error: %d", GetLastError());
      return(INIT_FAILED);
   }

   //--- Deliberately do NOT restore the last-processed-bar time. Re-arming it
   //    to "now" means the EA will wait for the next fully closed bar before
   //    evaluating any new entry signal after a (re)start - a safe default
   //    that avoids acting on a possibly stale condition.
   g_lastBarTime = iTime(_Symbol, InpTimeframe, 0);

   //--- best-effort initial ATR read so trailing stops work immediately,
   //    even before the first new bar arrives after (re)start
   double atrSeed[];
   ArraySetAsSeries(atrSeed, true);
   if(CopyBuffer(g_handleATR, 0, 1, 1, atrSeed) > 0)
      g_lastATR = atrSeed[0];

   int restored = CountOwnPositionsOnce();
   PrintFormat("%s initialized on %s (%s) | Magic=%I64u | Existing own position(s) found: %d",
               MQLInfoString(MQL_PROGRAM_NAME), _Symbol, EnumToString(InpTimeframe),
               InpMagicNumber, restored);

   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization                                           |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(g_handleFastMA != INVALID_HANDLE) IndicatorRelease(g_handleFastMA);
   if(g_handleSlowMA != INVALID_HANDLE) IndicatorRelease(g_handleSlowMA);
   if(g_handleATR    != INVALID_HANDLE) IndicatorRelease(g_handleATR);

   PrintFormat("%s deinitialized on %s. Reason=%d", MQLInfoString(MQL_PROGRAM_NAME), _Symbol, reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
{
   if(!IsTradingContextOK())
      return;

   //--- single pass: updates trailing stops AND caches own-position counts
   ScanOwnPositions();

   //--- only evaluate entry signals once per fully closed bar (efficiency
   //    and to avoid reacting to noise mid-bar)
   if(IsNewBar())
      CheckForNewSignal();
}

//+------------------------------------------------------------------+
//| Basic checks that trading is currently permitted at all           |
//+------------------------------------------------------------------+
bool IsTradingContextOK()
{
   if(!MQLInfoInteger(MQL_TRADE_ALLOWED))       return false;
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return false;
   if(!AccountInfoInteger(ACCOUNT_TRADE_ALLOWED))   return false;
   if(!AccountInfoInteger(ACCOUNT_TRADE_EXPERT))    return false;
   return true;
}

//+------------------------------------------------------------------+
//| Whether the symbol currently allows opening a new position in    |
//| the given direction (independent of the general checks above)    |
//+------------------------------------------------------------------+
bool CanOpen(bool isBuy)
{
   ENUM_SYMBOL_TRADE_MODE tm = (ENUM_SYMBOL_TRADE_MODE)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_MODE);
   if(tm == SYMBOL_TRADE_MODE_DISABLED || tm == SYMBOL_TRADE_MODE_CLOSEONLY) return false;
   if(tm == SYMBOL_TRADE_MODE_LONGONLY  && !isBuy) return false;
   if(tm == SYMBOL_TRADE_MODE_SHORTONLY &&  isBuy) return false;
   return true;
}

//+------------------------------------------------------------------+
//| Detects a newly closed bar on the signal timeframe                |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime t = iTime(_Symbol, InpTimeframe, 0);
   if(t == 0) return false; // history not ready yet
   if(t != g_lastBarTime)
   {
      g_lastBarTime = t;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Single pass over all open positions: updates trailing stops for  |
//| our own positions and tallies counts for use later this tick     |
//+------------------------------------------------------------------+
void ScanOwnPositions()
{
   g_ownTotal = 0;
   g_ownBuyCount = 0;
   g_ownSellCount = 0;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!m_position.SelectByIndex(i)) continue;
      if(m_position.Symbol() != _Symbol) continue;
      if(m_position.Magic()  != InpMagicNumber) continue;

      g_ownTotal++;
      if(m_position.PositionType() == POSITION_TYPE_BUY) g_ownBuyCount++;
      else                                                g_ownSellCount++;

      if(InpUseTrailingStop)
         UpdateTrailingStop();
   }
}

//+------------------------------------------------------------------+
//| One-off count of own positions (used only at startup for logging)|
//+------------------------------------------------------------------+
int CountOwnPositionsOnce()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!m_position.SelectByIndex(i)) continue;
      if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
         count++;
   }
   return count;
}

//+------------------------------------------------------------------+
//| Minimum allowed distance between price and SL/TP for this symbol |
//+------------------------------------------------------------------+
double GetMinStopDistance()
{
   long stopsLevel  = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   long freezeLevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_FREEZE_LEVEL);
   long minLevel    = MathMax(stopsLevel, freezeLevel);
   return (double)minLevel * _Point;
}

//+------------------------------------------------------------------+
//| Trails the SL of the currently-selected (m_position) position,   |
//| moving it only in the profitable direction, only once it has     |
//| improved by at least one trailing step, and only once price has  |
//| moved beyond the entry price.                                    |
//+------------------------------------------------------------------+
void UpdateTrailingStop()
{
   if(g_lastATR <= 0.0) return; // ATR not ready yet

   double posOpen = m_position.PriceOpen();
   double curSL   = m_position.StopLoss();
   double curTP   = m_position.TakeProfit();
   ulong  ticket  = m_position.Ticket();

   double trailDistance = g_lastATR * InpTrailingATRMultiplier;
   double trailStep     = g_lastATR * InpTrailingStepATR;
   double minStopDist   = GetMinStopDistance();

   if(m_position.PositionType() == POSITION_TYPE_BUY)
   {
      double bid   = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double newSL = NormalizeDouble(bid - trailDistance, _Digits);

      if(newSL <= posOpen) return;                              // not in profit beyond entry yet
      if(curSL > 0.0 && (newSL - curSL) < trailStep) return;    // improvement too small
      if((bid - newSL) < minStopDist) return;                   // broker would reject

      trade.PositionModify(ticket, newSL, curTP);
   }
   else if(m_position.PositionType() == POSITION_TYPE_SELL)
   {
      double ask   = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double newSL = NormalizeDouble(ask + trailDistance, _Digits);

      if(newSL >= posOpen) return;
      if(curSL > 0.0 && (curSL - newSL) < trailStep) return;
      if((newSL - ask) < minStopDist) return;

      trade.PositionModify(ticket, newSL, curTP);
   }
}

//+------------------------------------------------------------------+
//| Evaluates the entry signal on the just-closed bar.                |
//| >>> Replace the crossover logic below to use your own strategy. |
//+------------------------------------------------------------------+
void CheckForNewSignal()
{
   double fastMA[], slowMA[], atrBuf[];
   ArraySetAsSeries(fastMA, true);
   ArraySetAsSeries(slowMA, true);
   ArraySetAsSeries(atrBuf, true);

   // index 0 = current (incomplete) bar, 1 = last closed bar, 2 = bar before that
   if(CopyBuffer(g_handleFastMA, 0, 0, 3, fastMA) < 3) return;
   if(CopyBuffer(g_handleSlowMA, 0, 0, 3, slowMA) < 3) return;
   if(CopyBuffer(g_handleATR,    0, 0, 2, atrBuf) < 2) return;

   g_lastATR = atrBuf[1]; // ATR of the last fully closed bar

   bool crossUp   = (fastMA[2] <= slowMA[2] && fastMA[1] > slowMA[1]);
   bool crossDown = (fastMA[2] >= slowMA[2] && fastMA[1] < slowMA[1]);

   if(crossUp)
   {
      if(g_ownSellCount > 0)
         CloseAllOfType(POSITION_TYPE_SELL);

      if(g_ownBuyCount < InpMaxPositions && CanOpen(true))
         TryOpenPosition(true);
   }
   else if(crossDown)
   {
      if(g_ownBuyCount > 0)
         CloseAllOfType(POSITION_TYPE_BUY);

      if(g_ownSellCount < InpMaxPositions && CanOpen(false))
         TryOpenPosition(false);
   }
}

//+------------------------------------------------------------------+
//| Closes every own position of the given type (rare, event-driven, |
//| so an extra scan here does not affect per-tick efficiency)       |
//+------------------------------------------------------------------+
void CloseAllOfType(ENUM_POSITION_TYPE t)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!m_position.SelectByIndex(i)) continue;
      if(m_position.Symbol() != _Symbol) continue;
      if(m_position.Magic()  != InpMagicNumber) continue;
      if(m_position.PositionType() == t)
         ClosePosition(m_position.Ticket());
   }
}

//+------------------------------------------------------------------+
//| Closes a single own position by ticket, with limited retries     |
//+------------------------------------------------------------------+
void ClosePosition(ulong ticket)
{
   for(int attempt = 1; attempt <= InpMaxRetries; attempt++)
   {
      if(trade.PositionClose(ticket))
         return;

      uint rc = trade.ResultRetcode();
      PrintFormat("Close attempt %d for #%I64u failed: %u (%s)",
                  attempt, ticket, rc, trade.ResultRetcodeDescription());

      if(rc == TRADE_RETCODE_REQUOTE || rc == TRADE_RETCODE_PRICE_CHANGED || rc == TRADE_RETCODE_PRICE_OFF)
      {
         Sleep(InpRetryDelayMs);
         continue;
      }
      break; // non-retryable error
   }
}

//+------------------------------------------------------------------+
//| Sends a new market order sized by risk, with SL/TP derived from  |
//| ATR, margin/spread pre-checks, and limited retries                |
//+------------------------------------------------------------------+
void TryOpenPosition(bool isBuy)
{
   //--- spread filter (only gates NEW entries, never closes/trailing)
   if(InpMaxSpreadPoints > 0)
   {
      double spreadPoints = (SymbolInfoDouble(_Symbol, SYMBOL_ASK) - SymbolInfoDouble(_Symbol, SYMBOL_BID)) / _Point;
      if(spreadPoints > InpMaxSpreadPoints)
      {
         PrintFormat("%s: spread %.1f pts exceeds limit %d pts, skipping entry.", _Symbol, spreadPoints, InpMaxSpreadPoints);
         return;
      }
   }

   if(g_lastATR <= 0.0)
   {
      Print("ATR not yet available, skipping entry.");
      return;
   }

   double price = isBuy ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);

   double slDist = g_lastATR * InpATRMultiplierSL;
   double tpDist = InpATRMultiplierTP > 0.0 ? g_lastATR * InpATRMultiplierTP : 0.0;
   double minStopDist = GetMinStopDistance();
   if(slDist < minStopDist) slDist = minStopDist;
   if(tpDist > 0.0 && tpDist < minStopDist) tpDist = minStopDist;

   double sl = isBuy ? price - slDist : price + slDist;
   double tp = (tpDist > 0.0) ? (isBuy ? price + tpDist : price - tpDist) : 0.0;
   sl = NormalizeDouble(sl, _Digits);
   if(tp > 0.0) tp = NormalizeDouble(tp, _Digits);

   double lot = CalculateLotSize(slDist);
   if(lot <= 0.0)
   {
      Print("Calculated lot size is zero, skipping entry.");
      return;
   }

   //--- margin pre-check
   double marginRequired = 0.0;
   ENUM_ORDER_TYPE ot = isBuy ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
   if(OrderCalcMargin(ot, _Symbol, lot, price, marginRequired))
   {
      double freeMargin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
      if(marginRequired > freeMargin)
      {
         PrintFormat("Insufficient free margin (%.2f required, %.2f available), skipping entry.", marginRequired, freeMargin);
         return;
      }
   }

   bool sent = false;
   for(int attempt = 1; attempt <= InpMaxRetries && !sent; attempt++)
   {
      sent = isBuy ? trade.Buy(lot, _Symbol, 0.0, sl, tp, InpTradeComment)
                   : trade.Sell(lot, _Symbol, 0.0, sl, tp, InpTradeComment);

      if(!sent)
      {
         uint rc = trade.ResultRetcode();
         PrintFormat("Order send attempt %d failed: %u (%s)", attempt, rc, trade.ResultRetcodeDescription());

         if(rc == TRADE_RETCODE_REQUOTE || rc == TRADE_RETCODE_PRICE_CHANGED || rc == TRADE_RETCODE_PRICE_OFF)
         {
            Sleep(InpRetryDelayMs);
            continue;
         }
         break; // non-retryable error
      }
   }
}

//+------------------------------------------------------------------+
//| Position sizing: risk % of balance vs. SL distance, or fixed lot |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistPrice)
{
   double lot;

   if(InpRiskPercent <= 0.0 || slDistPrice <= 0.0)
   {
      lot = InpFixedLot;
   }
   else
   {
      double balance   = AccountInfoDouble(ACCOUNT_BALANCE);
      double riskMoney = balance * InpRiskPercent / 100.0;
      double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
      double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);

      if(tickValue <= 0.0 || tickSize <= 0.0)
      {
         lot = InpFixedLot; // fallback if symbol info unavailable
      }
      else
      {
         double lossPerLot = (slDistPrice / tickSize) * tickValue;
         lot = (lossPerLot > 0.0) ? (riskMoney / lossPerLot) : InpFixedLot;
      }
   }

   return NormalizeLot(lot);
}

//+------------------------------------------------------------------+
//| Rounds/clamps a lot size to the symbol's volume step/min/max     |
//+------------------------------------------------------------------+
double NormalizeLot(double lot)
{
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double step   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(step <= 0.0) step = 0.01;

   lot = MathRound(lot / step) * step;
   lot = MathMax(minLot, MathMin(maxLot, lot));

   int stepDigits = (int)MathRound(-MathLog10(step));
   if(stepDigits < 0) stepDigits = 0;
   if(stepDigits > 8) stepDigits = 8;

   return NormalizeDouble(lot, stepDigits);
}
//+------------------------------------------------------------------+